rails-app/config/routes.rb
Rails.application.routes.draw do

  resources :tenants
  root to: "members#index"
  get 'user_root', to: "users#index", as: "user_root"

  devise_for :user, skip: [:registrations]
  devise_scope :user do
     resources :users, path: "", only: [:new, :create], controller: "users" #-> url.com/users/new
  end
  resources :users

  get 'courses/open', to: "courses#open", as: "open_courses"
  resources :courses do |r|
    resources :tickets
  end

  get 'members/courses/:id', to: 'members#course', as: 'members_course'
  resources :members

  get 'settings', to: 'settings#index', as: 'settings'
  put 'settings', to: 'settings#update'

  get 'registrations/available', to: 'registrations#new', as: 'register'
  post 'registrations/:id/switch_role', to: 'registrations#switch_role', as: 'switch_role'
  post 'registrations/:id/set_status/:status', to: 'registrations#set_status', as: 'set_status'
  resources :registrations

  get 'api/:tenant/payments/:id/status', to: 'api#payment_status', as: "payment_status"
  post 'api/:tenant/payments/:id/webhook', to: 'api#payment_webhook', as: "payment_webhook"
  post 'api/:tenant/register', to: 'api#register', as: "api_register"
  get 'api/:tenant/courses', to: 'api#courses', as: "api_courses"
  get 'api/:tenant/courses/:id', to: 'api#course', as: "api_course"
  get 'api/:tenant/styles', to: 'api#styles', as: "api_styles"
  get 'api/:tenant/locations', to: 'api#locations', as: "api_locations"

  require 'sidekiq/web'

  mount Sidekiq::Web, at: "/sidekiq"
end

rails-app/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy, :members]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all.page(params[:page])
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new(roles: 1)
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def open
    today = Date.today
    @courses = Course.where("registration_start <= ? AND registration_end >= ?", today, today)
    render action: :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:title, :description, :roles, :location_list, :style_list, :registration_start, :registration_end)
    end
end

rails-app/app/helpers/courses_helper.rb
module CoursesHelper
end

rails-app/app/views/courses/_form.html.erb
<%= form_for(course) do |f| %>

  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

  <div class="row">
    <%= f.label :title %>
    <div class="col-xs-4 input-group"><%= f.text_field :title, class: "form-control" %></div>
  </div>

  <div class="row">
    <%= f.label :locations %>
    <div class="col-xs-4 input-group"><%= f.text_field :location_list, value: f.object.location_list.to_s, class: "form-control" %></div>
  </div>

  <div class="row">
    <%= f.label :styles %>
    <div class="col-xs-4 input-group"><%= f.text_field :style_list, value: f.object.style_list.to_s, class: "form-control" %></div>
  </div>

  <div class="row">
    <%= f.label :roles %>
    <b><%= @course.roles %></b>
    <div class="col-xs-4 input-group"><%= f.select :roles, Course.roles.keys.to_a.map{ |r| [r.gsub("_", " "), r] }, selected: @course.roles, class: "form-control" %></div>
  </div>

  <div class="row">
    <%= f.label :description %>
    <div class="col-xs-4 input-group"><%= f.text_area :description, class: "form-control" %></div>
  </div>

  <div class="row">
    <%= f.label :registration_start %>
    <div class="col-xs-4 input-group"><%= f.date_select :registration_start, class: "form-control" %></div>
  </div>

  <div class="row">
    <%= f.label :registration_end %>
    <div class="col-xs-4 input-group"><%= f.date_select :registration_end, class: "form-control" %></div>
  </div>

  <div class="row actions">
    <%= f.submit "Save", class: "btn btn-success" %>
  </div>
<% end %>

<% if course.errors.any? %>
  <div class="notice-holder row">
    <% course.errors.full_messages.each do |message| %>
      <p class="notice alert alert-danger"><%= message %></p>
    <% end %>
  </div>
<% end %>

rails-app/app/views/courses/edit.html.erb
<div class="row"><h1>Editing Course</h1></div>
<%= render 'form', course: @course %>

rails-app/app/views/courses/index.html.erb
<h1>Courses</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Start</th>
      <th>End</th>
      <th>Registrations</th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr data-link="<%= url_for(course) %>">
        <td><%= course.title %></td>
        <td><%= truncate(course.description, length: 40) %></td>
        <td><%= course.registration_start %></td>
        <td><%= course.registration_end %></td>
        <td>
          <% if course.roles == "lead_and_follow" %>
            <strong>Accepted:</strong>
            <%= "#{course.leads.where(status:"accepted").count} / #{course.follows.where(status:"accepted").count}" %>
            <br />
            <strong>Waitinglist:</strong>
            <%= "#{course.leads.where(status:"waitinglist").count} / #{course.follows.where(status:"waitinglist").count}" %>
            <br />
            <strong>Triage:</strong>
            <%= "#{course.leads.where(status:"triage").count} / #{course.follows.where(status:"triage").count}" %>
          <% elsif course.roles == "solo"%>
            <strong>Accepted:</strong>
            <%= "#{course.solos.where(status:"accepted").count}" %>
            <br />
            <strong>Waitinglist:</strong>
            <%= "#{course.solos.where(status:"waitinglist").count}" %>
            <br />
            <strong>Triage:</strong>
            <%= "#{course.solos.where(status:"triage").count}" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @courses %>

<br>

<%= link_to 'New Course', new_course_path, class: "btn btn-success" %>

rails-app/app/views/courses/new.html.erb
<div class="row"><h1>New Course</h1></div>
<%= render 'form', course: @course %>

rails-app/app/views/courses/show.html.erb
<h1><%= @course.title %></h1>
<p>
  <%= simple_format(@course.description) %>
</p>

<h4>Tags</h4>
<p>
  <strong>Locations:</strong>
  <%= @course.location_list %>
</p>
<p>
  <strong>Roles:</strong>
  <%= @course.roles.gsub("_", " ") %>
</p>
<p>
  <strong>Styles:</strong>
  <%= @course.style_list %>
</p>

<h4>Registration</h4>
<p>
  <strong>Start:</strong>
  <%= @course.registration_start %>
</p>
<p>
  <strong>End:</strong>
  <%= @course.registration_end %>
</p>

<%= link_to 'Edit', edit_course_path(@course), class:"btn btn-primary" %>
<%= link_to 'Destroy', @course, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>

<h2>Tickets</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Label</th>
      <th>Price</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @course.tickets.each do |ticket| %>
      <tr data-link="<%= edit_course_ticket_path(@course, ticket) %>">
        <td><%= ticket.label %></td>
        <td><%= ticket.price %></td>
        <td><%= link_to 'Remove', [@course, ticket], method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Add Ticket', new_course_ticket_path(@course), class: "btn btn-success" %>

<h2>Registrations</h2>
<p>
  <strong>Accepted (L/F):</strong>
  <%= "#{@course.leads.where(status:"accepted").count} / #{@course.follows.where(status:"accepted").count}" %>
  <br />
  <strong>Waitinglist (L/F):</strong>
  <%= "#{@course.leads.where(status:"waitinglist").count} / #{@course.follows.where(status:"waitinglist").count}" %>
  <br />
  <strong>Triage (L/F):</strong>
  <%= "#{@course.leads.where(status:"triage").count} / #{@course.follows.where(status:"triage").count}" %>
</p>
<%= render partial: 'registrations/registrations_table', locals: {registrations: @course.registrations.order(:created_at), roles: @course} %>

<div class="row">
  <h2>Export</h2>
  <%= link_to 'CSV', members_course_path(@course, format: "csv"), class: "btn btn-info" %>
  <%= link_to 'Excel', members_course_path(@course, format: "xls"), class: "btn btn-success" %>
</div>