rails-app/config/routes.rb
Rails.application.routes.draw do

  resources :tenants
  root to: "members#index"
  get 'user_root', to: "users#index", as: "user_root"

  devise_for :user, skip: [:registrations]
  devise_scope :user do
     resources :users, path: "", only: [:new, :create], controller: "users" #-> url.com/users/new
  end
  resources :users

  get 'courses/open', to: "courses#open", as: "open_courses"
  resources :courses do |r|
    resources :tickets
  end

  get 'members/courses/:id', to: 'members#course', as: 'members_course'
  resources :members

  get 'settings', to: 'settings#index', as: 'settings'
  put 'settings', to: 'settings#update'

  get 'registrations/available', to: 'registrations#new', as: 'register'
  post 'registrations/:id/switch_role', to: 'registrations#switch_role', as: 'switch_role'
  post 'registrations/:id/set_status/:status', to: 'registrations#set_status', as: 'set_status'
  resources :registrations

  get 'api/:tenant/payments/:id/status', to: 'api#payment_status', as: "payment_status"
  post 'api/:tenant/payments/:id/webhook', to: 'api#payment_webhook', as: "payment_webhook"
  post 'api/:tenant/register', to: 'api#register', as: "api_register"
  get 'api/:tenant/courses', to: 'api#courses', as: "api_courses"
  get 'api/:tenant/courses/:id', to: 'api#course', as: "api_course"
  get 'api/:tenant/styles', to: 'api#styles', as: "api_styles"
  get 'api/:tenant/locations', to: 'api#locations', as: "api_locations"

  require 'sidekiq/web'

  mount Sidekiq::Web, at: "/sidekiq"
end

rails-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LindyAdmin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <a class="navbar-brand" href="/">LindyAdmin</a>
        </div>


        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li role="presentation"><%= link_to 'Members', members_path %></li>
            <li role="presentation"><%= link_to 'Courses', courses_path %></li>
            <li role="presentation"><%= link_to 'Settings', settings_path %></li>
            <% if user_signed_in? and current_user.superadmin? %>
              <li role="presentation"><%= link_to 'Users', user_root_path %></li>
            <% end %>
            <li role="presentation"><%= link_to 'Registration form example', register_path %></li>
          </ul>
          <p class="navbar-text navbar-right">
            <% if user_signed_in? %>
              Signed in as <strong><%= link_to current_user.email, destroy_user_session_path, method: :delete %></strong>.
            <% else %>
              <%= link_to "Login", new_user_session_path %>
            <% end %>
          </p>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    
    <% if flash[:notice] -%>
    <div class="notice-holder row">
      <p class="notice alert alert-success"><%= notice %></p>
    </div>
    <% end %>
    <% if flash[:alert] -%>
    <div class="notice-holder row">
      <p class="notice alert alert-error"><%= notice %></p>
    </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:page_js) %>
  </body>
</html>