rails-app/config/routes.rb
Rails.application.routes.draw do

  resources :tenants
  root to: "members#index"
  get 'user_root', to: "users#index", as: "user_root"

  devise_for :user, skip: [:registrations]
  devise_scope :user do
     resources :users, path: "", only: [:new, :create], controller: "users" #-> url.com/users/new
  end
  resources :users

  get 'courses/open', to: "courses#open", as: "open_courses"
  resources :courses do |r|
    resources :tickets
  end

  get 'members/courses/:id', to: 'members#course', as: 'members_course'
  resources :members

  get 'settings', to: 'settings#index', as: 'settings'
  put 'settings', to: 'settings#update'

  get 'registrations/available', to: 'registrations#new', as: 'register'
  post 'registrations/:id/switch_role', to: 'registrations#switch_role', as: 'switch_role'
  post 'registrations/:id/set_status/:status', to: 'registrations#set_status', as: 'set_status'
  resources :registrations

  get 'api/:tenant/payments/:id/status', to: 'api#payment_status', as: "payment_status"
  post 'api/:tenant/payments/:id/webhook', to: 'api#payment_webhook', as: "payment_webhook"
  post 'api/:tenant/register', to: 'api#register', as: "api_register"
  get 'api/:tenant/courses', to: 'api#courses', as: "api_courses"
  get 'api/:tenant/courses/:id', to: 'api#course', as: "api_course"
  get 'api/:tenant/styles', to: 'api#styles', as: "api_styles"
  get 'api/:tenant/locations', to: 'api#locations', as: "api_locations"

  require 'sidekiq/web'

  mount Sidekiq::Web, at: "/sidekiq"
end

rails-app/app/models/member.rb
class Member < ApplicationRecord
  has_many :registrations, dependent: :destroy
  has_many :courses, through: :registrations

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, presence: true, format: { with: Devise.email_regexp, message: "Invalid email" }

  def full_name
    "#{self.firstname} #{self.lastname}"
  end

  def self.to_csv(members, options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      members.each do |member|
        csv << member.attributes.values_at(*column_names)
      end
    end
  end
end

rails-app/app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  before_action :set_course, only: [:course]
  helper_method :sort_column, :sort_direction

  # GET /members
  # GET /members.json
  def index
    @members = Member.all.order(sort_column + " " + sort_direction).page(params[:page])

    respond_to do |format|
      format.html
      format.csv { send_data Member.to_csv(@members), filename: "Members.csv" }
      format.xls { send_data Member.to_csv(@members, col_sep: "\t"), filename: "Members.xls" }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def course
    members = @course.participants.order(sort_column + " " + sort_direction).page(params[:page])

    respond_to do |format|
      format.html
      format.csv { send_data Member.to_csv(members), filename: "#{@course.title}_participants.csv" }
      format.xls { send_data Member.to_csv(members, col_sep: "\t"), filename: "#{@course.title}_participants.xls" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:firstname, :lastname, :email)
    end

    def sort_column
      Member.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end
end

rails-app/app/helpers/members_helper.rb
module MembersHelper
end

rails-app/app/views/members/_form.html.erb
<%= form_for(member) do |f| %>

  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

  <div class="row">
    <%= f.label :firstname %>
    <div class="col-xs-4 input-group"><%= f.text_field :firstname, class: "form-control" %></div>
  </div>

  <div class="row">
    <%= f.label :lastname %>
    <div class="col-xs-4 input-group"><%= f.text_field :lastname, class: "form-control" %></div>
  </div>

  <div class="row">
    <%= f.label :email %>
    <div class="col-xs-4 input-group"><%= f.text_field :email, class: "form-control" %></div>
  </div>

  <div class="row actions">
    <%= f.submit "Save", class: "btn btn-success" %>
  </div>
<% end %>


<% if member.errors.any? %>
  <div class="notice-holder row">
    <% member.errors.full_messages.each do |message| %>
      <p class="notice alert alert-danger"><%= message %></p>
    <% end %>
  </div>
<% end %>

rails-app/app/views/members/_members_table.html.erb
<% can_sort ||= false %>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th><%= can_sort ? sortable("firstname") : "firstname"%></th>
      <th><%= can_sort ? sortable("lastname") : "lastname"%></th>
      <th><%= can_sort ? sortable("email") : "email"%></th>
    </tr>
  </thead>

  <tbody>
    <% members.each do |member| %>
      <tr data-link="<%= url_for(member) %>">
        <td ><%= member.firstname %></td>
        <td ><%= member.lastname %></td>
        <td ><%= member.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

rails-app/app/views/members/edit.html.erb
<div class="row"><h1>Editing Member</h1></div>
<%= render 'form', member: @member %>

rails-app/app/views/members/index.html.erb
<h1>Members</h1>
<%= render partial: 'members_table', locals: {members: @members, can_sort: true} %>
<div class="row">
  <%= paginate @members %>
</div>

<div class="row">
  <%= link_to 'New Member', new_member_path, class: "btn btn-success" %>
</div>

<div class="row">
  <h2>Export</h2>
  <%= link_to 'CSV', members_path(format: "csv"), class: "btn btn-info" %>
  <%= link_to 'Excel', members_path(format: "xls"), class: "btn btn-success" %>
</div>

rails-app/app/views/members/new.html.erb
<div class="row"><h1>New Member</h1></div>
<%= render 'form', member: @member %>

rails-app/app/views/members/show.html.erb
<h1>
  <%= @member.firstname %> <%= @member.lastname %>
</h1>
<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<%= link_to 'Edit', edit_member_path(@member), class: "btn btn-primary" %>
<%= link_to 'Destroy', @member, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>

<h2>Registrations</h2>
<%= render partial: 'registrations/registrations_table', locals: {registrations: @member.registrations} %>